### ISSUE TITLE
(-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

### ISSUE THREAD

**Issue by Dinesh317** [llSourcell/Object_Detection_demo_LIVE#6]
Traceback (most recent call last):
  File "demo.py", line 132, in <module>
    result = find_strawberry(image)
  File "demo.py", line 63, in find_strawberry
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

**Comment by xaggi** [comment]
Hi, did you solve it? I am having the same issue here :(

**Comment by hollowstrawberry** [comment]
I'm pretty sure it just means the image doesn't exist. I fixed the path when opening the image and it worked for me.

**Comment by pblxptr** [comment]
I have the same issue, but fixing the path does not work for me.

**Comment by hollowstrawberry** [comment]
Due to the cause of the error in my case, you might want to double check that the image isn't None, or in an otherwise invalid state I suppose (though about that I wouldn't know)

**Comment by pblxptr** [comment]
The image isn't None. I can show it. It occurs when I'm trying to convert image from RGBA to GRAY.

**Comment by ArmoredReaper** [comment]
I'm getting the same error, even when using the full path to the image. Someone else I know had the same problem and fixed it by moving the pictures, but I can't get it to work no matter what I try. (FYI working on a Mac, not sure if that changes anything)

**Comment by hollowstrawberry** [comment]
When I next got this error (or a very similar one at least) it was because I was trying to make my own image with a numpy array. It probably doesn't help in your cases, but I realized each pixel has to be on its own sublist, like so: [[[a,b,c]], [[a,b,c]], [[a,b,c]]]

Try printing your image to the console to see if it makes sense

**Comment by Hitsaa** [comment]
I also had the same issue. Actually I had mistakenly typed wrong name of image file in my code that I was trying to import. But when I typed the right name of file then this issue was solved.

**Comment by shravankumar9892** [comment]
I also had the same issue, I solved it like this...
Remember if the RGB values of the images ranges from 0-255 make sure that the values are of data type 'uint8' and not float. **RGB values should be float only when it range from 0-1** . So if the RGB values are float type and range from 0-255, what happens is opencv thinks as its float values should lie between 0-1 and hence it clips off the value. Hence do this:
`image = image.astype('uint8')`

**Comment by shravankumar9892** [comment]
Even I had the same problem, and the solution was quiet easy. Remember 1 thing, if the RGB values of your image lie in the range of 0-255, make sure the values are not of data type 'float'. As OpenCV considers float only when values range from 0-1. If it finds a float value larger than 1 it clips off the value thinking floats only exsist between 0-1. Hence such errors generated. So convert the data type to uint8 if values are from 0-255.
`image = image.astype('uint8')`
Check this [Kaggle Kernal](https://www.kaggle.com/shravankumar9892/colorization-dataset?scriptVersionId=6320113)

**Comment by Sannndy0000** [comment]
I met the same problem and found that this occurred to me simply because I   commented out 2 lines:
```
if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```
Getting them back made it work.

**Comment by JH-Xie** [comment]
I solved this problem by use x = np.asarray(x, dtype=np.uint8) before do the conversion

**Comment by vivek-kumar9696** [comment]
hey...
This issue can also happen, not due to a problem with the code, but if another application is using the same webcam to capture video, or if another application which is using the same webcam was not closed properly.
Eg. when i had this problem, it was due to me running the code from jupyter notebook after I had just before run it from Spyder. Although the imshow windows were destroyed, the code from spyder was still capturing video from the same webcam as that of Jupyter's.
This caused absence of any video through the notebook and hence the image was a Nonetype

**Comment by rozeappletree** [comment]
> I solved this problem by use x = np.asarray(x, dtype=np.uint8) before do the conversion

for this code, i used your instruction :

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    frame = np.asarray(frame, dtype=np.uint8)
    
    
    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

i am getting error : int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Soumyatrivedi3099** [comment]
error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper' 
i have this same error and i dont know how to remove it.

**Comment by shubhambagwari** [comment]
Try this once,
cap = cv2.VideoCapture(0) #O is for internal camera. 
cap = cv2.VideoCapture(1) #1 is for external camera.

**Comment by ahmad70967** [comment]
I have this problem when working with png images only

**Comment by ZP-Guo** [comment]
I get this error because of a stupid bug. I use LSP dataset to train some nets recently and this bug that you discuss comes. What something wrong. I find it for two days. And I find "im00001.jpg" was changed into "img00001.jpg" by myself. 
So maybe it is just a little bug that I can not get it as soon as I can.

**Comment by mahdidrm** [comment]
> Try this once,
> cap = cv2.VideoCapture(0) #O is for internal camera.
> cap = cv2.VideoCapture(1) #1 is for external camera.

Yeeees... thank you ! I am working on a code that wrote on labtop and I am running it on my PC... I use 1 and it works !!!! thanks a lot

**Comment by Dhurub007** [comment]
get the same error while using trackbar in opencv but after this method it resolved
img = np.full((512,512,3), 12, np.uint8)

**Comment by SCF-byter** [comment]
I had exactly the same error.
Basically, it happend because I accidentally put Greyscale images into cv2.cvtColor(image, cv2.COLOR_BGR2RGB). So make sure you are definitively putting in color images (i.e. images with three channels)

**Comment by 14-purva** [comment]
rror: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<1,-1,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'
can somebody help me out with this error.....

**Comment by 14-purva** [comment]
error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<1,-1,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'
can somebody help me out with this error....

**Comment by Faguilar-V** [comment]
> I have the same issue, but fixing the path does not work for me.

Yes, only change the path work

**Comment by Zaniyar** [comment]
Non of the above solved my problem. 

What I noticed is, when I use pyCharm or Code I get those errors. 
In pyCharm:
```
  rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2BGRA)
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'
```

in Code:
```Abort trap: 6 ```

I tested: I have everywhere the same env and same python version.

Solution for me:

**When I run the code in the standalone terminal, it works fine.**

I tried also to run Code as admin (with sudo on the terminal, but got same errors).

**Comment by alirezarf** [comment]
> 
> 
> error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<1,-1,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'
> can somebody help me out with this error....

https://github.com/statueofmike/rtsp/issues/9

**Comment by Michal2207** [comment]
I've got the same error. I fixed it by using two '\\' in the file path instead of one '\'.

**Comment by rafaelmsales27** [comment]
I had the same problem, I was sure the path was right.

My problem was in the cv2.imread I had before the color conversion. 

Since I am getting the image from a file instead of cv2.VideoCapture.

My code was as follows:

```
# x is my path
for x in list_of_paths:
        raw_img = cv2.imread(x)
        raw_img_colored = cv2.cvtColor(raw_img, COLOR_BayerRG2RGB)
```

The solution was to put the cv2.IMREAD_UNCHANGED (or -1) inside the cv2.imread method as follows:

```
# x is my path
for x in list_of_paths:
        raw_img = cv2.imread(x, -1)
        raw_img_colored = cv2.cvtColor(raw_img, COLOR_BayerRG2RGB)
```

Hope it helps!
